### ISSUE TITLE
Integrating Collections as a Network Graph

### ISSUE THREAD

**Issue by ianmilligan1** [web-archive-group/WALK#15]
One early task is to take our derivative network graphs (which are in `data/derivatives/links`) and see if there is any merit to visualizing them together in a program like Gephi.

I was thinking we might get @greebie to take the output files, see if maybe we can ingest each collection as a set of nodes, and look for overlaps? As a networks export, it might be a good opening project with some autonomy.

i.e. take our Idle No More collection and our Canadian Prairies collection, plot them up with classes based on their respective collections, see how they play together.

**Comment by ianmilligan1** [comment]
Cool, @greebie checked in [a script here](https://github.com/web-archive-group/WALK/blob/master/Scripts/pseudo_code.txt), in pseudo code.

```
#1. Get base addresses for each file.
#2. Initial comparison operations:
##  - for two or three collections, compare with venn diagram
##  - for three or more, use correspondence analysis to see which collections have
##    the most in common.
#3. Set AB = A %i% B; A = A - (A %i% B); B = B - (A %i% B) (for two comparison)
#4. Set ABC = A %i% B %i% C; AB = A %i% B - (ABC)  (etc.)
#5. Create table out of base addresses vs collections.
##  - decide if you want weighted programs. Does it make sense to include how frequently each site was crawled including # of pages?
##  - plot Chi-squared distance using mca library.
#6. Develop script to construct edgelist / graph.
#7. Save as graphml file for use in gephi.
```

I think this looks really interesting! Once the cloud maintenance window passes, why don't you pick two collections that looks to be an appropriate size, @greebie, and we can try this out! First with two, then with three?

**Comment by greebie** [comment]
I've created a branch that will examine a collections and use either a venn diagram or correspondence analysis to determine which collections have the most interesting common connections.  I'd like to try this a number of different ways - 1. through links 2. through common words 3. through common entity types (eg. names or locations).

**Comment by greebie** [comment]
Closed because the core functionality described in the pseudo code has been merged and pulled.  New features can be released as new notes.
