### ISSUE TITLE
Redo WebArchives.ca to become WALK homepage

### ISSUE THREAD

**Issue by ianmilligan1** [web-archive-group/WALK#17]
Reframe the CPP collection as a prototype for forthcoming WALK project, change home page to include abstract, about page, etc.

Please put other suggestions for changes here!

**Comment by ianmilligan1** [comment]
First kick at the can is here: http://webarchives.ca. Still need to update bios and do lots more.

**Comment by gsharder** [comment]
Nice!

On Sun, Jun 5, 2016 at 7:44 PM, Ian Milligan notifications@github.com
wrote:

> First kick at the can is here: http://webarchives.ca. Still need to
> update bios and do lots more.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/web-archive-group/WALK/issues/17#issuecomment-223852482,
> or mute the thread
> https://github.com/notifications/unsubscribe/AEOggoMqPeiJPBFodxvgXa-E8tqrdEcyks5qI3t3gaJpZM4Is7pa
> .

## 

_Geoff HarderAssociate University Librarian_

Digital Initiatives, University of Alberta Libraries
2-10H Cameron Library, University of Alberta
Edmonton, AB, Canada T6G 2J8
780.492.7914 (o)

_geoffrey.harder@ualberta.ca geoffrey.harder@ualberta.ca
library.ualberta.ca http://library.ualberta.ca_
