### ISSUE TITLE
Biographies

### ISSUE THREAD

**Issue by ianmilligan1** [web-archive-group/WALK#23]
I'd like to get folks from the University of Alberta and Compute Canada to provide bios for the new redesign of WebArchives.ca, now that we're going to use it as the WALK project home. Could each of you please provide a bio and a link, if appropriate, to a homepage or something along those lines? Thanks!

**Comment by GeoffreyRockwell** [comment]
How is this,

Dr. Geoffrey Martin Rockwell is a Professor of Philosophy and Humanities Computing at the University of Alberta <geoffreyrockwell.com>. He has published on textual visualization and analysis, and computing in the humanities including a book the MIT Press, Hermeneutica: Computer-Assisted Interpretation in the Humanities. He is a co-developer of Voyant Tools <voyant-tools.org>, a suite of text analysis tools, and leads the TAPoR <tapor.ca> project documenting text tools. He is currently the Director of the Kule Institute for Advanced Study and blogs at <theoreti.ca>.

Short bio and lots of links,

Geoffrey R.

**Comment by umarqasim** [comment]
Here is my brief bio:

Dr. Umar Qasim is the Digital Preservation Officer at the University of
Alberta Libraries and responsible for the libraries digital preservation
program. He maintains and shares expertise on digital preservation with the
University of Alberta Libraries, the University community, and the
professional community of practice in large. His research interests lie in
the areas of digital preservation, wireless sensor networks, information
retrieval, information filtering, text mining and optimization. For more
information visit <umarqasim.ca>

_--_
_Umar Qasim, PhD_
Digital Preservation Officer
2-10N Cameron Library | University of Alberta
Edmonton, Alberta T6G 2J8, Canada
Tel: 780-492-9861 | Fax: 780-492-9243
umar.qasim@ualberta.ca | http://www.umarqasim.ca

**Comment by tsuomela** [comment]
Dr. Todd Suomela is CLIR-DLF Postdoctoral Fellow for Data Curation in the Sciences and Social Sciences at the University of Alberta. He works on collection assessment, project management, web archive education, documentation, and research outreach. He studies the use of web archives in scholarly research, crowdsourcing in the humanities and sciences, and research data management across disciplines. He has published and presented on citizen science, digital humanities, web archiving, and data quality. His personal website is at toddsuomela.com and he can be followed on Twitter @tsuomela.

**Comment by gsharder** [comment]
Geoff Harder is Associate University Librarian at the University of Alberta Libraries (UAL). His responsibilities include strategic development of UAL's digital initiatives, which includes research data management, repositories, and digital scholarship support. Geoff serves on a number of national and international data and preservation organizations, including the National Executive Committee for the Consortia for Advancing Standards in Research Administrative Data (CASRAI), the Board of Directors for the CLOCKSS preservation network (an extension of Stanford's LOCKSS technology), and the Advisory Committee committee for the Public Knowledge Project (PKP) based out of Simon Fraser University. Geoff has been actively involved in the development of the web archiving program at the University of Alberta since its beginning in 2010.

**Comment by ghost** [comment]
Sam Popowich is Discovery Systems Librarian at the University of Alberta Libraries. He is responsible for the libraries' discovery strategy, including Blacklight implementation. GitHub, Twitter: @redlibrarian

**Comment by ianmilligan1** [comment]
Added and relaunched site with bios!

**Comment by sfbetz** [comment]
Sorry all - this flew by in my GitHub notifications while I was away, and
dropped to the bottom of the pile.

Sonya Betz is Digital Initiatives Projects Librarian at the University of
Alberta Libraries. She is responsible for the project management and
coordination of a wide range of digital initiatives, and is the service
manager for UAL's journal publishing program. She works with project teams
to define and integrate end-user needs into application development, and
has published and presented on user experience in digital repositories and
discovery tools.

I'll ping @pbinkley to do the same...

On Mon, Jul 4, 2016 at 10:55 AM, Ian Milligan notifications@github.com
wrote:

> Added and relaunched site with bios!
> 
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> https://github.com/web-archive-group/WALK/issues/23#issuecomment-230327401,
> or mute the thread
> https://github.com/notifications/unsubscribe/AMNT8s5t0SXw-oPgN7qowaxEEIJ38-2Nks5qSTrugaJpZM4ItGrO
> .

## 

Sonya Betz
Digital Initiatives Projects Librarian

_University of Alberta Libraries2-10U Cameron Library, University of
AlbertaEdmonton, AB, Canada T6G 2J8  *
*sonya.betz@ualberta.ca sfbetz@ualberta.ca *
*780-492-1718_

**Comment by ianmilligan1** [comment]
Great thanks @sfbetz - will add in the next batch tomorrow!

**Comment by pbinkley** [comment]
Sorry about that - here's mine:

Peter Binkley is the Digital Initiatives Technology Librarian at the University of Alberta Libraries. He leads the Digital Initiatives development team in various collaborations with librarians and other stakeholders, to develop repository and preservation services and systems for the library's digital collections.

**Comment by ianmilligan1** [comment]
Perfect thanks! It'll be up shortly.

**Comment by ianmilligan1** [comment]
Added @sfbetz @pbinkley
