### ISSUE TITLE
Date Extraction from Text or HTML

### ISSUE THREAD

**Issue by tsuomela** [web-archive-group/WALK#24]
- User story: I want to study the change in discourse over time for a given site or set of sites but I do not have access to retrospective crawls for the sites in question. I do have access to a new crawl performed recently of the sites I'm interested in studying. Many of these sites attach dates and times to the content they publish, for example in a blog or news site. So I want to extract the dates from the published content and link those dates to the content.
- Approaches: the date information could be extracted from multiple sources within the content. Regular expressions could be use to pattern match against common date formats - DD/MM/YYYY, etc.; word matches could be used for searching for months, seasons, decades, centuries, etc. - Jan, January, winter, first quarter; URLs could be examined for regular patterns - YYYY/MM/DD/.
- Outputs: the date information could be output to a JSON file that includes a document ID, extracts a la KWIC format; date information could also be attached to the index data in Solr/Blacklight.

**Comment by ianmilligan1** [comment]
We've been talking about doing something, although the non-systematic nature of this makes it very difficult. My sense is that rather than mucking about with the WARCs, maybe generate plain-text index/plain-text files and work from there?
