### ISSUE TITLE
Comparing Names, Organizations, Locations (NER)

### ISSUE THREAD

**Issue by ianmilligan1** [web-archive-group/WALK#28]
Generate names, places, locations – once done for test collections (ELXN42, CPP two scrapes), send to @greebie.

**Comment by ianmilligan1** [comment]
@greebie I've added in the location data (which has been cleaned up via OpenRefine and put into a CSV). If you want to play with the fusion tables, you can find the maps [in this post](https://ianmilligan.ca/2016/08/04/plotting-and-comparing-locations-mentioned-in-a-web-archive-warcbase-openrefine-and-google-fusion-tables/). 

Organizations and persons should be up pretty soon. I'll wait until they're done as a batch before putting them in the repo and pinging you again!

**Comment by greebie** [comment]
Thanks Ian.  Is it possible to have one more collection to play with?  Maybe a small one for time purposes - I just want the script to be able to move to Correspondence analysis (which means I need 4).  It can be as messy as you like.

**Comment by greebie** [comment]
Hi Ian, 

~~I might have killed your commit after merging.  I think I assumed the NER addition was already master - sorry about that.  Can you please resend?  Thanks.~~

(fixed - kept in Compare branch)

**Comment by ianmilligan1** [comment]
@greebie Sure - let me think on this and put it into the queue. Maybe an Alberta politics-esque collection?

**Comment by ianmilligan1** [comment]
@greebie Also, just pushed up the stuff I also had on the master branch so we've merged the two, should be good now.

**Comment by greebie** [comment]
Yes - one or more additional Alberta-esque collections would be great.

**Comment by ianmilligan1** [comment]
I'll run this after we do the full URL extraction (might take the weekend, I think, as it's a pretty intensive job that's occupying WALK). Do you have a collection in mind @greebie, based on the ones that you've worked with on the other `compare` work? Let me know and I'll queue up a script so we can get some of this info to you next week.

**Comment by ianmilligan1** [comment]
OK, I'm creating one of the `alberta_education_curriculum-201204.txt` collection now.

**Comment by ianmilligan1** [comment]
Done and done. Noted in Slack but you can find it here: https://github.com/ianmilligan1/McLuhan/tree/master/NER/openrefine-frequencies.

**Comment by ianmilligan1** [comment]
This was generated and passed along to @greebie!
