### ISSUE TITLE
Correspondence Analysis by Dates

### ISSUE THREAD

**Issue by ianmilligan1** [web-archive-group/WALK#29]
Comparing collection by crawl dates.

**Comment by ianmilligan1** [comment]
We got a working prototype of this up. At some point, can we share that notebook in this repo @greebie? Will keep issue open until that point.

**Comment by greebie** [comment]
I pushed an example.  I'll close for now with the promise of prettier examples to come!

**Comment by ianmilligan1** [comment]
Great. Did you push to the `compare` branch? I'm not seeing it there.

**Comment by greebie** [comment]
Ah I see.   Just to master.  Compare's behind a bit now, although I am working on some 3 dimensional plots for the date stuff.

**Comment by greebie** [comment]
I think the prototype is complete for this.  Since incorporating new methods to the Compare class is listed elsewhere, I'm going to close this one.
