### ISSUE TITLE
Broken WARC in Canadian Labour

### ISSUE THREAD

**Issue by ianmilligan1** [web-archive-group/WALK#37]
Just putting this here so I can track it. We have a broken WARC somewhere in the Canadian Labour collection. I will start trying to hunt it down. 

[Error message is here](https://gist.github.com/ianmilligan1/e2e59695d1f0b5601ea28342902dc4a4), Invalid Distance Code.

In the future, @ruebot and I were thinking we should try to think of some way to validate WARCs beforehand (i.e. beyond just relying on the MD5 checksum).

**Comment by ianmilligan1** [comment]
First try [was with the Warcat library](https://pypi.python.org/pypi/Warcat/), but both 'healthy' and 'unhealthy' WARC files have validation problems. So need to keep looking.

**Comment by jeffersonbailey** [comment]
Hmm. Let us know if we can help. Something in the transfer maybe or just something bad on disk?

**Comment by ianmilligan1** [comment]
Thanks @jeffersonbailey, really appreciated. We're trying to chase it down. It wasn't a broken `.warc.gz` file (in that it passed tests). We've isolated the file, so I'll know more soon... I'll keep you posted.

**Comment by ianmilligan1** [comment]
[This recent warcbase commit](https://github.com/lintool/warcbase/commit/8a34bd04702044cba5aa11504384cea1aa104981) handled the error, so collection working now!
