### ISSUE TITLE
Scale the Compare Class

### ISSUE THREAD

**Issue by greebie** [web-archive-group/WALK#40]
The current class does a good job of creating a plot, but I'd like to do a few different things with it that relate more directly to the test cases.  Here is a summary list:
- [x] Determine the kinds of outputs for comparison (eg. compare by links, compare by NER output) 
- [ ] Two layers of analysis, three layers of analysis, or more
- [ ] Graph into 2 or 3 dimensions
- [x] Cumulative graph
- [ ] Produce a graph or just the analysis.
- [ ] If it's a collection analysis tool, maybe the class could help with the analysis a bit (eg. point out outliers, provide warnings for potential data problems etc.)

**Comment by ianmilligan1** [comment]
This sounds great. I've turned the above into a list to keep track of things. 

Let me know if you need some data, want somebody to test it, etc. etc. Happy to help however I can!

**Comment by greebie** [comment]
Have been thinking about this.  Since we now have about 6 notebooks that rely on the current version of Compare, it might be better to fork the Compare class to a separate Repo and start a version 0.1 with these features.  I'm just thinking that if I start messing with the main class now, it will start to break our work describing the collections.  What do you think?

**Comment by ianmilligan1** [comment]
I think that makes sense to me – a lot of sense, actually, since it won't break the work we've done so far. 👍

**Comment by greebie** [comment]
Closing this issue as a problem for Compare 0.1.0 found here:  https://github.com/greebie/Compare
