### ISSUE TITLE
Create dummy collections for testing

### ISSUE THREAD

**Issue by greebie** [web-archive-group/WALK#44]
Using the compare tool, will create a dummy based on the websites that are present in a large number of sites (the size will depend on the number of collections - so far with 38 collections, it looks like urls with 16+ cross-links will produce about 100 or so website urls.

These urls will content-analysized for the following categories
- Government (eg. gc.ca)
- Social media  (twitter.com)
- Technology sites (adobe.com, bit.ly)
- Organizations (w3.org)
- Media (wsj.com)

With the dummy collection, that's 6 dummy categories.

**Comment by ianmilligan1** [comment]
I think we've developed this – if so, @greebie do you mind closing the issue (or providing an update if you want to keep it open!).
