### ISSUE TITLE
Final Tweaks to Correspondence Analysis

### ISSUE THREAD

**Issue by ianmilligan1** [web-archive-group/WALK#47]
A few more things to get the correspondence analysis fully tested:
- [x] Add in the Toronto Labour Unions collection and the Toronto Political Parties collection, both of which are long-standing collections to see if they skew results;
- [x] Include frequencies for four new collections (as discussed in #46)
- [x] Try frequency with 1000 words instead of 150 (or tweak with it to get it going)
- [x] Try to remove overlaps in visualizations - [perhaps drawing on this](http://stackoverflow.com/questions/19073683/matplotlib-overlapping-annotations-text) - example notebook [here](https://github.com/Phlya/adjustText/blob/master/examples/Examples.ipynb)?

**Comment by ianmilligan1** [comment]
Ping @greebie

**Comment by greebie** [comment]
I have the fix for overlaps in the word-based analysis, but am going to forgo it for the urls.  I'd rather include it as a function in the new Compare class.

**Comment by greebie** [comment]
Hey I completed this without realizing.  Going to close.
