### ISSUE TITLE
Tools to Install?

### ISSUE THREAD

**Issue by ianmilligan1** [web-archive-group/WALK#5]
This is a catch-all issue for tools people would like to be installed on the CC Cloud. We'll start with:
- [Warcbase](https://github.com/lintool/warcbase)
- [Internet Archive ARS-Workshop](https://github.com/vinaygoel/ars-workshop)
- [UKWA Shine](https://github.com/ukwa/shine)

If there is something else you'd like me to get installed, please let me know here.

**Comment by pbinkley** [comment]
How about [tensorflow](https://www.tensorflow.org/)? I haven't tried it myself, but John Fink's reports on Twitter last week made it look interesting.

**Comment by ianmilligan1** [comment]
Looks and sounds great, thanks @pbinkley!

**Comment by greebie** [comment]
Hi Ian, as you know, I've been using Anaconda for Python 3, so that might be a half-decent inclusion.
