### ISSUE TITLE
Write Up for Each Collection

### ISSUE THREAD

**Issue by ianmilligan1** [web-archive-group/WALK#56]
I've been playing around with our new site, and the new idea is to have a landing page per institution, broken down by collection. For each collection, I'd like to have a paragraph of text describing the collection.

Research assistants will do this by (a) creating Gephi files (#42); (b) consulting our Crawl Visualizations available at <https://github.com/web-archive-group/WALK-CrawlVis>:
- what sites are in it? A quick summary of its coverage.
- what time period does it cover, and how comprehensively?
- any weird crawl issues - a coverage spike or not? (from crawl visualization)

We'll then have links under the text to:
- derivative files;
- Archive-It page;
- library unit creating the collections, etc.

Anything you think I am missing out? This will be one of the major RA tasks this summer.

**Comment by ianmilligan1** [comment]
Mock-up here.
<img width="819" alt="screen shot 2017-01-12 at 5 07 18 pm" src="https://cloud.githubusercontent.com/assets/3834704/21932511/e34ba9ce-d96e-11e6-9220-b98c69dc4397.png">

**Comment by greebie** [comment]
I think this is a great idea.  Is it possible that there is metadata for the collections already in the WARC files?  It seems like there should be, and it could be an easy way to show the grad students what a WARC is.

**Comment by ianmilligan1** [comment]
Unfortunately I think we'll have to do that manually, as there's no real metadata within the WARCs pertaining to overall collection data and scope. But yeah, I wish there was.

What the workflow will probably be:
- students consult Archive-It page;
- students render network diagram, taking screenshot and making a few quick notes of the major hubs;
- students consult crawl visualization, domain-by-domain breakdown;

Which they then write a paragraph out of?

**Comment by ianmilligan1** [comment]
We've achieved this milestone!
